In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import kmeans_plusplus, KMeans

# Image preprocessing

In [2]:
img = cv2.cvtColor(cv2.imread("data/kid.jpeg"), cv2.COLOR_BGR2RGB)

# resizing the data
img = cv2.resize(img, (306, 382))
img.shape

(382, 306, 3)

In [3]:
plt.imshow(img)
plt.axis("off")
plt.show()

In [12]:
X = img.reshape((-1, 3))
X.shape

(116892, 3)

In [17]:
X[:,:1]

array([[158],
       [170],
       [177],
       ...,
       [ 83],
       [ 88],
       [ 92]], dtype=uint8)

In [21]:
# ploting the first 20 points of X
fig = plt.figure()
ax = plt.axes(projection='3d')
ax.scatter3D(X[:20,0:1], X[:20, 1:2], X[:20, 2:])

# Model

In [29]:
k = 10
model = KMeans(n_clusters=k)
model.fit(X)

KMeans(n_clusters=10)

In [30]:
centroids = model.cluster_centers_
centroids

array([[ 51.18201322,  57.07925041,  96.71907702],
       [241.17833554, 243.07771907, 243.63892558],
       [166.36645719,  41.81565855,  43.54647814],
       [ 39.08964264,  29.80942286,  39.11555767],
       [154.56850434, 150.41007999, 189.81843984],
       [ 41.06662419, 115.34975927, 177.99270745],
       [202.21109878, 120.59112098, 118.16315205],
       [189.32462971, 112.47595053,   9.91281112],
       [101.41881519,  37.23361543,  28.20370006],
       [105.06054953,  86.27849389, 129.71955563]])

In [31]:
# converting the centroids to color numpy array
# unit8 is good data type as it lies b/w 0-255
# colors: RGB format colors
colors = np.array(centroids, dtype='uint8')
colors

array([[ 51,  57,  96],
       [241, 243, 243],
       [166,  41,  43],
       [ 39,  29,  39],
       [154, 150, 189],
       [ 41, 115, 177],
       [202, 120, 118],
       [189, 112,   9],
       [101,  37,  28],
       [105,  86, 129]], dtype=uint8)

# Getting the colors

In [33]:
# showing colors by using subplots
i = 1
for color in colors:
    plt.subplot(1,k,i)
    i += 1
    plt.axis("off")
    mat = np.zeros((100,100,3), dtype='uint8')
    mat[:, :, :] = color
    plt.imshow(mat)

plt.show()
